### NumPy

### 1.Create a 1D array from a list.

In [19]:
import numpy as np
num_list=[5,3,8]
arr1=np.array(num_list)
arr1

array([5, 3, 8])

### 2. Create a 3x3 array of zeros.

In [2]:
zero_arr=np.zeros((3,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3. Create a 2x2 array of ones.

In [3]:
one_arr=np.ones((2,2))
one_arr

array([[1., 1.],
       [1., 1.]])

### 4. Generate array from 0 to 10 (exclusive).

In [4]:
arr2=np.arange(0,10,1)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 5. Create 5 evenly spaced numbers between 0 and 1.

In [5]:
even_sp_arr=np.linspace(0,1,5)
even_sp_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 6. Create a 4x4 identity matrix.

In [6]:
idn_matrix=np.eye(4)
idn_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 7. Reshape 1D array to 2D.

In [7]:
arr3=np.array([1,2,3,4,5,6])
reshp1dTo2d=arr3.reshape((3,2))
reshp1dTo2d

array([[1, 2],
       [3, 4],
       [5, 6]])

### 8. Get the shape and dtype of an array.

In [8]:
arr3=np.array([1,2,3,4,5,6])
arr3.shape

(6,)

In [9]:
arr3.dtype

dtype('int32')

### 9. Reverse a NumPy array.

In [10]:
arr3=np.array([1,2,3,4,5,6])
rev_arr3=arr3[::-1]
rev_arr3

array([6, 5, 4, 3, 2, 1])

### 10. Extract even numbers from an array.

In [11]:
even_arr=arr3[arr3%2==0]
even_arr

array([2, 4, 6])

### 11. Find the max in each row.

In [12]:
arr4=np.array([[3,5,6,1],[0,1,6,10],[2,5,4,8]])
max_row=arr4.max(axis=1)
print("Original array :\n",arr4)
print("Maximum numbers in each row are :",max_row)

Original array :
 [[ 3  5  6  1]
 [ 0  1  6 10]
 [ 2  5  4  8]]
Maximum numbers in each row are : [ 6 10  8]


### 12. Compute the mean, std, and median of an array.

In [13]:
mean_arr4=np.mean(arr4)
std_arr4=np.std(arr4)
median_arr4=np.median(arr4)
print(f" Mean: {mean_arr4} \n Standard deviation: {std_arr4} \n Median: {median_arr4}")

 Mean: 4.25 
 Standard deviation: 2.890357532670771 
 Median: 4.5


### 13. Stack two arrays vertically.

In [14]:
arr1=np.array([[5,3,8],[2,7,1]])
arr3=np.array([[9,7,3],[4,8,2]])
np.concatenate((arr1,arr3),axis=1) 

array([[5, 3, 8, 9, 7, 3],
       [2, 7, 1, 4, 8, 2]])

### 14. Stack two arrays horizontally.

In [15]:
arr1=np.array([[5,3,8],[2,7,1]])
arr3=np.array([[9,7,3],[4,8,2]])
np.concatenate((arr1,arr3),axis=0) 

array([[5, 3, 8],
       [2, 7, 1],
       [9, 7, 3],
       [4, 8, 2]])

### 15. Find the unique values and their counts.

In [16]:
arr4=np.array([[3,5,6,1],[0,1,6,10],[2,5,4,8]])
unique_values,counts=np.unique(arr4,return_counts=True)
print(f" Unique values: {unique_values}\n Counts: {counts}")

 Unique values: [ 0  1  2  3  4  5  6  8 10]
 Counts: [1 2 1 1 1 2 2 1 1]


### 16. Replace NaN with column means.

In [26]:
r_data1=np.array([[250,np.nan],[175,300],[np.nan,220]])
col_mean1=np.nanmean(r_data1,axis=0)
r_data_fill1=np.where(np.isnan(r_data1),col_mean1,r_data1)
print(f"Original Array:\n{r_data1}")
print(f"Array after NaN values replaced by column means:\n{r_data_fill1}")

Original Array:
[[250.  nan]
 [175. 300.]
 [ nan 220.]]
Array after NaN values replaced by column means:
[[250.  260. ]
 [175.  300. ]
 [212.5 220. ]]


### 17. Get index of min and max values.

In [22]:
gim_arr=np.array([6,3,8,2,0,7])
ind_min=np.argmin(gim_arr)
ind_max=np.argmax(gim_arr)
print(f"Original array: {gim_arr}")
print("Index of minimum value :",ind_min)
print("Index of maximum value :",ind_max)

Original array: [6 3 8 2 0 7]
Index of minimum value : 4
Index of maximum value : 2


### 18. Create a 3D array of random integers.

In [25]:
rand_3D_arr=np.random.randint(100,size=(3,2,3))
rand_3D_arr

array([[[82, 50, 78],
        [98, 71, 84]],

       [[45, 47, 53],
        [76, 75, 45]],

       [[19, 94,  9],
        [85, 91, 81]]])

### 19. Use np.where() to replace values.

In [27]:
r_data2=np.array([[250,np.nan],[175,300],[315,220]])
#col_mean=np.nanmean(r_data,axis=0)
r_data_fill2=np.where(np.isnan(r_data2),278,r_data2)
print(f"Original Array:\n{r_data2}")
print(f"After replacement of NaN values the Array:\n{r_data_fill2}")

Original Array:
[[250.  nan]
 [175. 300.]
 [315. 220.]]
After replacement of NaN values the Array:
[[250. 278.]
 [175. 300.]
 [315. 220.]]


### Pandas 

### 1. Create a Series using a Python list.

In [1]:
import pandas as pd
ser1=pd.Series([10,20,30,40,50])
ser1

0    10
1    20
2    30
3    40
4    50
dtype: int64

### 2. Create a Series with custom string indices.

In [2]:
ser1=pd.Series([10,20,30,40,50],index=["A","B","C","D","E"])
ser1

A    10
B    20
C    30
D    40
E    50
dtype: int64

### 3. Create a Series from a dictionary.

In [3]:
expense_dict={'Rent':2500,'Grocery':3000,'Transport':2000,'Insurance':5000}
expense_series=pd.Series(expense_dict)
expense_series

Rent         2500
Grocery      3000
Transport    2000
Insurance    5000
dtype: int64

### 4. Access first 3 elements of a Series.

In [5]:
expense_series[:3]

Rent         2500
Grocery      3000
Transport    2000
dtype: int64

### 5. Filter Series elements greater than 50.

In [7]:
ser2=pd.Series([20,40,60,80])
filtered_ser2=ser2[ser2>50]
filtered_ser2

2    60
3    80
dtype: int64

### 6. Add two Series with different indices.

In [10]:
ser1=pd.Series([10,20,30,40,50],index=["A","B","C","D","E"])
ser2=pd.Series([10,200,300,400,500],index=["a","b","c","d","e"])
ser1.add(ser2,fill_value=0)

A     10.0
B     20.0
C     30.0
D     40.0
E     50.0
a     10.0
b    200.0
c    300.0
d    400.0
e    500.0
dtype: float64

### 7. Multiply a Series by a scalar.

In [12]:
ser1=pd.Series([10,20,30,40,50],index=["A","B","C","D","E"])
print(f"Original series:\n{ser1}\nAfter scalar multiplication, Series is:\n{ser1*2}")

Original series:
A    10
B    20
C    30
D    40
E    50
dtype: int64
After scalar multiplication, Series is:
A     20
B     40
C     60
D     80
E    100
dtype: int64


### 8. Use .multiply() method to multiply with scalar.

In [13]:
ser1=pd.Series([10,20,30,40,50],index=["A","B","C","D","E"])
print(f"Original series:\n{ser1}\nAfter scalar multiplication, Series is:\n{ser1.multiply(2)}")

Original series:
A    10
B    20
C    30
D    40
E    50
dtype: int64
After scalar multiplication, Series is:
A     20
B     40
C     60
D     80
E    100
dtype: int64


### 9. Sort Series by values descending.

In [17]:
print(f"Before sorting, Series is:\n{ser1}")
print(f"Before sorting, Series is:\n{ser1.sort_values(ascending=False)}")

Before sorting, Series is:
A    10
B    20
C    30
D    40
E    50
dtype: int64
Before sorting, Series is:
E    50
D    40
C    30
B    20
A    10
dtype: int64


### 10. Sort Series by index.

In [18]:
ser3=pd.Series([70,50,10,30,80],index=["m","j","l","k","n"])
ser3.sort_index()

j    50
k    30
l    10
m    70
n    80
dtype: int64

### 11. Check for null values.

In [20]:
ser4=pd.Series([70,50,10,np.nan,80],index=["m","j","l","k","n"])
ser4.isnull()

m    False
j    False
l    False
k     True
n    False
dtype: bool

### 12. Concatenate two Series using concat()

In [22]:
ser1=pd.Series([10,20,30,40,50],index=["A","B","C","D","E"])
ser2=pd.Series([10,200,300,400,500],index=["a","b","c","d","e"])
pd.concat([ser1,ser2])

A     10
B     20
C     30
D     40
E     50
a     10
b    200
c    300
d    400
e    500
dtype: int64

### 13. Concatenate two Series using append().

In [24]:
ser1=pd.Series([10,20,30])
ser2=pd.Series([40,50])
#append() is deprecated now.
#ser1.append(ser2,ignore_index=True)

### 14. Retrieve first 5 elements using .head()

In [26]:
df=pd.DataFrame(['Python','Numpy','Pandas','Matplotlib','Statistics','ML Algorithm','Deep Learning'])
df.head(5)

0
0      Python
1       Numpy
2      Pandas
3  Matplotlib
4  Statistics

### 15. Retrieve last 5 elements using .tail()

In [28]:
df1=pd.DataFrame(['Python','Numpy','Pandas','Matplotlib','Statistics','ML Algorithm','Deep Learning'])
df1.tail(5)

0
2         Pandas
3     Matplotlib
4     Statistics
5   ML Algorithm
6  Deep Learning

### 16. Convert Series to DataFrame.

In [30]:
ser2=pd.Series([20,40,60,80])
df2=ser2.to_frame()
df2

0
0  20
1  40
2  60
3  80

### 17. Replace NaN with 0.

In [33]:
ser5=pd.Series([1,2,np.nan,5,8,np.nan])
new_ser5=ser5.fillna(0)
new_ser5

0    1.0
1    2.0
2    0.0
3    5.0
4    8.0
5    0.0
dtype: float64

### 18. Drop missing values.

In [34]:
ser5=pd.Series([1,2,np.nan,5,8,np.nan])
new_ser5=ser5.dropna()
new_ser5

0    1.0
1    2.0
3    5.0
4    8.0
dtype: float64

### 19. Check Series data type.

In [36]:
ser5=pd.Series([1,2,np.nan,5,8,np.nan])
new_ser5.dtype

dtype('float64')